FROM node:14.16.1

WORKDIR /app

COPY package.json /app

RUN npm install -g --force yarn
RUN yarn install

COPY ./ /app/

ARG FRONTEND_ENV=production

ENV VUE_APP_ENV=${FRONTEND_ENV}

# Comment out the next line to disable tests
# RUN yarn run test -- --browsers ChromeHeadlessNoSandbox --watch=false

ARG configuration=production

RUN yarn build --configuration $configuration

ENV HOST 0.0.0.0

CMD ["yarn", "start"]
