default_context:
  project_name: 'bii-vue2'
  project_slug: 'bii-vue2'
  domain_main: 'bii-vue2.com'
  domain_staging: 'stag.bii-vue2.com'
  docker_swarm_stack_name_main: 'bii-vue2-com'
  docker_swarm_stack_name_staging: 'stag-bii-vue2-com'
  secret_key: 'test'
  first_superuser: 'admin@bii-vue2.com'
  first_superuser_password: 'test2'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.bii-vue2.com", "https://stag.bii-vue2.com", "https://bii-vue2.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: 'smtp.gmail'
  smtp_user: 'marouane.sanhaji@gmail.com'
  smtp_password: 'Lilya@09302013'
  smtp_emails_from_email: 'info@bii-vue2.com'
  postgres_password: 'test3'
  pgadmin_default_user: 'admin@bii-vue2.com'
  pgadmin_default_user_password: 'test2'
  traefik_constraint_tag: 'bii-vue2.com'
  traefik_constraint_tag_staging: 'stag.bii-vue2.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:test2'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
